# This file was generated by GoReleaser. DO NOT EDIT.
cask "spec-graph" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "5d7bf465b811e5f7ffe7a296818b3a709f474c93bf740bcc02b3036c881f2ebf"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "46c7c4700b5acee70966925e3539c94636ebf489dd73afbe366cce9f296652d9"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a21e083cb8d0ceec13ca21e3403d9dcbfa0e79275d7d98e776d28ef6decf1875"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3a80550e8b009a325e3d982b35e2e76b287ffce4314a5eec071237a7bba052ef"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_arm64.tar.gz"
    end
  end

  name "spec-graph"
  desc "Typed specification graph CLI for managing requirements, decisions, and phases"
  homepage "https://github.com/tyeongkim/spec-graph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spec-graph"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
