# This file was generated by GoReleaser. DO NOT EDIT.
cask "spec-graph@beta" do
  version "0.4.0-beta.7"

  on_macos do
    on_arm do
      sha256 "c1c0fd37a0a6ad26fbd0ca76087a892695bedf5b442eb7496a2eddad20744804"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "262ac909f1fac79d7658457774b99cacbf5123b5a0f888eb64a4b5d2aadce23a"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "953ebe35acf0303645908081b1a4e9cb666158a19b7d495300ab517906aea15c"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc5cb42e0b0382012ac6c39c593ed1ee06302401ed712ad202544edba5a55b31"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_x86_64.tar.gz"
    end
  end

  name "spec-graph@beta"
  desc "Typed specification graph CLI for managing requirements, decisions, and phases (beta channel)"
  homepage "https://github.com/tyeongkim/spec-graph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spec-graph"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required
end
