# This file was generated by GoReleaser. DO NOT EDIT.
cask "spec-graph" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_x86_64.tar.gz"
      sha256 "394867b963450a102e36fb2784a61865f868dc83dac9f43faa337a9b34ed6777"
    end
    on_arm do
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_arm64.tar.gz"
      sha256 "ecca53fa198936c42ed7788c8566bc5b32c1faa3ffadb6bbfc8e458bd4598558"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_x86_64.tar.gz"
      sha256 "e8d60bdfa80abaccac7029bdac3499e122d7a9f86112aeadcb0517c5eefdf5f2"
    end
    on_arm do
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_arm64.tar.gz"
      sha256 "35c0a5465e13db0e2c3bc959dcc4970d3e588f7c462d96074569a63e3c6d1ae3"
    end
  end

  name "spec-graph"
  desc "Typed specification graph CLI for managing requirements, decisions, and phases"
  homepage "https://github.com/tyeongkim/spec-graph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spec-graph"

  # No zap stanza required

end
