# This file was generated by GoReleaser. DO NOT EDIT.
cask "spec-graph@beta" do
  version "0.4.0-beta.8"

  on_macos do
    on_arm do
      sha256 "a487a07aeca448a80abcb2a8a4a372b5a200f7beff58640780db88d3d0f616c8"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a189509f8ac534efd8729290a40104e01fe2c26143c49d56aebf92ac256e4dd0"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d2fa2ec6a9e982c545ec397e61b6f9236da0ec25ad5cc22e525851721111fa47"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "76c93799abed06174c118f6526c7dd692cd3af4cf92508100fbdc2b7b06602a5"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_x86_64.tar.gz"
    end
  end

  name "spec-graph@beta"
  desc "Typed specification graph CLI for managing requirements, decisions, and phases (beta channel)"
  homepage "https://github.com/tyeongkim/spec-graph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spec-graph"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required
end
