# This file was generated by GoReleaser. DO NOT EDIT.
cask "spec-graph@beta" do
  version "0.4.0-beta.2"

  on_macos do
    on_intel do
      sha256 "d63667b7f1730579ebade0fa74588bc29090cc06f2f0012186e87d2755689251"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "347a1bbeb69bde5b112e0d7760758ec2d661de5a98bd91b04a7ea20847b642d8"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "526b6399f9da8ec2037ec03d87758f37bf201ce99e1942710296f4963ce1f602"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "99ee3e07e2be4f27003d3bee894ad89d4320d26a323f30f4da7a4fefb1e560e2"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_arm64.tar.gz"
    end
  end

  name "spec-graph@beta"
  desc "Typed specification graph CLI for managing requirements, decisions, and phases (beta channel)"
  homepage "https://github.com/tyeongkim/spec-graph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spec-graph"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
