# This file was generated by GoReleaser. DO NOT EDIT.
cask "spec-graph" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "61f24b7cab16ad035b0753f52664c6bf88b41af12111b5b185aa640fe88bfb6d"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d685fd10ee47867fab38603d1ea4992ef3663cf4694ed6442643937ffe4a7017"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3b633494289543e72b8d8db820df35ad2867a73b9507463148cc267d49fac943"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cdf92d0ca450c34c7fe521f9ce489f0efaa727fa42886cf5384f2d4160755813"
      url "https://github.com/tyeongkim/spec-graph/releases/download/v#{version}/spec-graph_Linux_arm64.tar.gz"
    end
  end

  name "spec-graph"
  desc "Typed specification graph CLI for managing requirements, decisions, and phases"
  homepage "https://github.com/tyeongkim/spec-graph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spec-graph"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
